pipeline {
    agent any

    parameters {
        choice(name: 'action', choices: ['plan', 'apply', 'destroy'], description: 'Pick action')
    }

    environment {
        TF_VAR_yc_zone = credentials('yc_zone')
        TF_VAR_yc_cloud_id = credentials('yc_cloud_id')
        TF_VAR_yc_folder_id = credentials('yc_folder_id')
        TF_VAR_yc_token = credentials('yc_token')
        TF_VAR_pb_ssh_keys = credentials('pb_ssh_keys')
        TF_VAR_pvt_ssh_key = credentials('pvt_ssh_key')
        TEL_CHATID = credentials('tl_chatId')
    }

    tools {
        terraform 'terraform14'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout(
                    [$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/korshun06/OTUS_IaC/']]
                    ]
                )
            }
        }

        stage('TF Init token TC') {
            steps {
                withCredentials([file(credentialsId: 'tf_backend_token', variable: 'TF_CLOUD_TOKEN')]){
                    sh 'rm -f ~/.terraformrc'
                    sh 'cp ${TF_CLOUD_TOKEN} ~/.terraformrc'
                }
            }
        }

        stage('TF Init') {
            steps {
                sh 'terraform -chdir=terraform/ init'
            }
        }      

        stage('TF Plan') {
            when {
                expression { 
                    return params.action == 'plan'
                }
            }
            steps {
                sh 'terraform -chdir=terraform/ plan > tr_plan.txt'
                archiveArtifacts artifacts: 'tr_plan.txt'
                telegramUploader(chatId: "${TEL_CHATID}", filter: 'tr_plan.txt', caption: "Terraform change plan from job '${env.JOB_NAME}'", silent: true, failBuildIfUploadFailed: false)
            }
        }
        
        stage('TF Apply') {
            when {
                expression { 
                    return params.action == 'apply'
                    
                }
            }
            steps {
                sh 'terraform -chdir=terraform/ apply -auto-approve > tr_apply.txt'
                archiveArtifacts artifacts: 'tr_apply.txt'
                telegramUploader(chatId: "${TEL_CHATID}", filter: 'tr_apply.txt', caption: "Terraform infrastructure changes from job '${env.JOB_NAME}", silent: true, failBuildIfUploadFailed: false)
            }
        }
        
        stage('TF Destroy') {
            when {
                expression { 
                    return params.action == 'destroy'
                }
            }
            steps {
                sh 'terraform -chdir=terraform/ destroy -auto-approve > tr_destroy.txt'
                archiveArtifacts artifacts: 'tr_destroy.txt'
                telegramUploader(chatId: "${TEL_CHATID}", filter: 'tr_destroy.txt', caption: "Removing the terraform infrastructure from the job '${env.JOB_NAME}", silent: true, failBuildIfUploadFailed: false)
            }
        }
    }

    post {
        always {
            cleanWs()
            sh 'rm -f ~/.terraformrc'
        }
    }
}