---
# file: upd-servers.yml
- hosts: all
  gather_facts: 'False'
  tasks:
    - name: Ansible | Install packages
      apt:
        name:
          - 'nano'
          - 'git'
        state: present
        update_cache: 'True'
