---
# file: upd-servers.yml
- hosts: all
  gather_facts: False
  tasks:
    - name: Ansible | Update all packages to their latest version
      apt:
        # name: "*"
        # state: latest
        update_cache: yes

    - name: Ansible | Install packages
      package:
        name:
          - 'nano'
          - 'git'
        state: present